
server:
  port: 8003

spring:
  application:
    name: yz-mall-seata-account
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://159.75.135.41:3306/mall_account?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: mall_account
    password: JGtYGjcwGcTwFTEK
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.3.77:8848

seata:
  application-id: ${spring.application.name}
  # seata 服务分组，要与服务端配置service.vgroup_mapping的后缀对应
  tx-service-group: t_mall_tx_group
  service:
    vgroup-mapping:
      t_mall_tx_group: guangzhou
  registry:
    type: nacos
    nacos:
      application: seata-server
      group: SEATA_GROUP
      server-addr: 192.168.3.77:8848
  config:
    type: nacos
    nacos:
      server-addr: 192.168.3.77:8848
      namespace: f0357fda-3e2d-42ae-ac6f-3848aaecf0db
      group: SEATA_GROUP
      data-id: seataServer.properties
#      context-path: /nacos