server:
  port: 10003

rocketmq:
  name-server: 192.168.3.237:9876
  producer:
    group: mall-demo-producer
    # 发送消息超时时间（毫秒），默认3000，建议设置为10000以上
    send-message-timeout: 10000
    # 最大消息大小（字节），默认4MB
    max-message-size: 4194304
    # 发送失败重试次数
    retry-times-when-send-failed: 2
    # 异步发送失败重试次数
    retry-times-when-send-async-failed: 2
  consumer:
    group: mall-demo-consumer